from src.config.target_game import (
    DEFAULT_VIEWPORT,
    GAME_ROOT_SELECTOR,
    GAME_STATE_LABEL_SELECTOR,
    PRIMARY_ACTION_SELECTOR,
    TARGET_GAME_URL,
)

__all__ = [
    "TARGET_GAME_URL",
    "DEFAULT_VIEWPORT",
    "GAME_ROOT_SELECTOR",
    "GAME_STATE_LABEL_SELECTOR",
    "PRIMARY_ACTION_SELECTOR",
]
